### ISSUE TITLE
Обрушается сборка в AppVeyor с кодом 126

### ISSUE THREAD

**Issue by Skitovich** [Skitovich/api_auto#4]
CI на базе AppVeyor закончилась ошибкой: Command exited with code 126 Build failed
**Окружение**
Java 14, [.appveyor.yml](https://github.com/Skitovich/api_auto/blob/main/.appveyor.yml), [build.gradle](https://github.com/Skitovich/api_auto/blob/main/build.gradle)

**Шаги:**
1.Создать пустой репозиторий на GitHub для проекта AppVeyor.
2.Открыть проект с лекции в InelliJ IDEA
3.Настроить CI для проекта GitHub AppVeyor в личном кабинете на сайте AppVeyor с помощью "+ADD"
4. Создать в IntelliJ IDEA папку artifacts
5. Поместить в папку файл app-mbank.jar
6. Добавить файл app-mbank.jar в отслеживаемый git'ом с помощью команды git add -f artifacts/app-mbank.jar
7. Создать в главном каталоге файл .appveyor.yml
8. Добавить в файл .appveyor.yml настройки:
PostmanEcho/.appveyor.yml

![appveyorBug](https://user-images.githubusercontent.com/69163937/99523730-80f95300-29a8-11eb-8bbb-19ccbdd3ca88.jpg)

9.Запустить тесты с помощью IntelliJ IDEA, удостовериться, что тесты проходят успешно
10.Разместить проект в созданном удаленном репозитории AppVeyor на GitHub
11. Наблюдать результат проверки CI в личном кабинете на сайте CI AppVeyor
Ожидаемый результат:
Тесты в IntelliJ IDEA проходят успешно
Сборка CI AppVeyor заканчивается результатом Build success
Фактический результат:
Тесты в IntelliJ IDEA проходят успешно
Сборка CI AppVeyor заканчивается результатом: Command exited with code 126 Build failed
appveyorBug

**Comment by andrew-pahomov** [comment]
При формировании проекта допущено несколько ошибок        
1. Отсутствует файл gradle-wrapper.jar в папке ./gradle/wrapper/        
2. В файле .appveyor.yml неверные настройки запуска сборок для веток репозитория       
3. В файле .appveyor.yml отсутствует команда `chmod +x gradlew` для предоставления прав на запуск скрипту        

В Ваш репозиторий выполнены пулл реквесты: [fix main](https://github.com/Skitovich/api_auto/pull/5) и [fix Json schema](https://github.com/Skitovich/api_auto/pull/6) для демонстрации верных настроек
